### ISSUE TITLE
Connection to Multiple BLE Devices

### ISSUE THREAD

**Issue by VinayTShetty** [android/connectivity-samples#10]
I am finding difficulty in modifying the code to connect to multiple  device.
Help Appreciated

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate
