### ISSUE TITLE
had to change minSdkVersion from 11 to 14 to get build

### ISSUE THREAD

**Issue by Rick-Majpruz** [android/connectivity-samples#106]
Have recent Android Studio installed. When trying to build this project, got this error:

    Error:Execution failed for task ':Application:processDebugManifest'.
    > Manifest merger failed : uses-sdk:minSdkVersion 11 cannot be smaller than version 14 declared in library [com.android.support:gridlayout-v7:26.1.0] /Users/sam/.android/build-cache/7731a640b1cec22163a95c6373df629a0c26f92d/output/AndroidManifest.xml
    Suggestion: use tools:overrideLibrary="android.support.v7.gridlayout" to force usage

So I edited Application/build.gradle and changed `minSdkVersion 11` to `minSdkVersion 14`.

Then the build completed and I was able to run the app.

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
