### ISSUE TITLE
MainActivity not implementing DownloadCallback

### ISSUE THREAD

**Issue by benjaminBrownlee** [android/connectivity-samples#107]
When I build this project, I get a couple errors, including this around the declaration of the main class:

    public class MainActivity extends FragmentActivity implements DownloadCallback { ... }

_Class 'MainActivity' must either be declared in abstract or implement method 'updateFromDownload(T)' in 'DownloadCallback'_

I found this error odd as the `MainActiivty` clearly implemented this method below, but I found it had its own errors:

    @Override
    public void updateFromDownload(String result) {
        if (result != null) {
            mDataText.setText(result);
        } else {
            mDataText.setText(getString(R.string.connection_error));
        }
    }

_Method does not override method from its superclass_

So how can this example code not implement the `DownloadCallback` interface because it lacks a necessary method that links the two (`updateFromDownload(T)`), but claim that the method cannot be overriden because it doesn't exist in its superclass?

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
