### ISSUE TITLE
Value to show reading 

### ISSUE THREAD

**Issue by craighemming** [android/connectivity-samples#11]
Hi I'm trying to understand java and am using this sample Gatt to enable me to connect to a BLE device and read the values i.e. temperature as an example and I can connect to device and see a value but its coming up with a hex value does anyone know how I change this. I'm not familiar with this and I have read forums but I don't know what to change to get what I want to achieve has anyone got any advice?

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate
