### ISSUE TITLE
can there be a manual to this app 

### ISSUE THREAD

**Issue by raunak-many-ac** [android/connectivity-samples#128]
after i installed the app on two devices both devices can only find each other using bluetooth i want them to be with wifi. I am a novice in wireless connection so please help me whether:
*the app is not meant to  working with wifi, 
*or, we need a third hotspot to which the two devices with apps will be connected to,
* or, one of the devices will be the hotspot,
* or it will automatically detect the connections available
* or it uses wifi direct
Please i need to figure it out for my project. Thank in advance

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate
