### ISSUE TITLE
react native failed resolution lcom/google/android//gms/nearby/messages/message

### ISSUE THREAD

**Issue by rares-lupascu** [android/connectivity-samples#129]
hi

i ma trying to implement google nearby into a react native app and i am getting this error ... i know it is most probably because of some conflicts in react native but i am trying my luck here ... any idea on how to approach this?
![image](https://user-images.githubusercontent.com/3641866/44569353-c0fa0d00-a782-11e8-9637-217149bce4fc.png)

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate
