### ISSUE TITLE
onBleSignalChanged() and onDistanceChanged() functions are not being triggered

### ISSUE THREAD

**Issue by akshay0297** [android/connectivity-samples#130]
I have recently started working of this Nearby Messages API and Beacons. I tried the demo app which is working fine but when I modified the code by adding the other two functions of MessageListener Class i.e onBleSignalChanged() and onDistanceChanged() I coundn't see any significant changes in the functioning of the application. Even though I moved the beacons towards(or away from) the smartphone, those functions were not getting triggered despite the change in distance and the RSSI values. I wanted to trigger a specific event once the distance value crosses a threshold which I set.  

Override
public void onBleSignalChanged(final Message message, final BleSignal bleSignal) 
{

    Log.i(TAG, "Message: " + message + " has new BLE signal information: " + bleSignal);

  }

 Override
  public void onDistanceChanged(final Message message, final Distance distance)
 {

    Log.i(TAG, "Distance changed, message: " + message + ", new distance: " + distance);

  }

Here is the code snippet that I have used.
Is there a specific reason for these functions to not get triggered ?

Thank You

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate
