### ISSUE TITLE
App crashes on sending payloads in a separate thread

### ISSUE THREAD

**Issue by shortstheory** [android/connectivity-samples#131]
I am using Nearby Connections v2.0 with my ConnectionsClient running in a BG Service. I am trying to send file payloads in a separate thread, I get an error with something along the lines of 'Endpoint channel not found for payload ID XXXXXX'. This causes the app to repeatedly crash and restart. Is there any way to send file payloads in a separate thread without this crash occurring?

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
