### ISSUE TITLE
WiFi Direct not working after Factory Reset

### ISSUE THREAD

**Issue by k-cube** [android/connectivity-samples#133]
I am using Nearby api on two android tablets to send files between them. They can connect to each other successfully but after doing a factory reset on both devices (that is how our customers receive the device), WiFi direct cannot be established and it throws java.io.FileNotFoundException: /data/misc/wifi/networkHistory.txt (No such file or directory). Then After connecting devices to a WiFi it eventually works. Any idea what to do with this issue?

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
