### ISSUE TITLE
Device doesn't connect twice to the same endpoint

### ISSUE THREAD

**Issue by KonsomeJona** [android/connectivity-samples#135]
I'm sorry if I'm just missing something.
I have an advertiser running on one smartphone. I have a discover running on another smartphone. 

When they both get close, they connect to each other and exchange data correctly.
Then, with the discover, I'm going away and as expected both the advertiser and discover loose the connection between each other. 
However, if I come back close to the advertiser, they won't again detect and exchange data eacher until I reset one of them. 

I'm practically using the same example code given here:
https://developers.google.com/nearby/connections/overview

Is there any reason why is it happening like this?

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
