### ISSUE TITLE
Question - Can this handle video stream from server device's camera?

### ISSUE THREAD

**Issue by abselt** [android/connectivity-samples#136]
Hello, I'm trying to use nearby connections to stream camera preview from one device to another but I'm not sure if this can be done by this lib so I'm asking you and here is a question with code of what i have tried:
[https://stackoverflow.com/questions/46849851/google-nearby-video-stream-clients-surfaceview-blank](https://stackoverflow.com/questions/46849851/google-nearby-video-stream-clients-surfaceview-blank) 
can you please point me out

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
