### ISSUE TITLE
get the closest device from different messages

### ISSUE THREAD

**Issue by yanisbourabaa** [android/connectivity-samples#137]
I have multiple devices in a room publishing messages.
I go in this room with my phone and would like to pair with the closest emitter.
is it possible to compare distances ?
or just shorten the signal range to 2meters (with DISTANCE_TYPE_EARSHOT my range is 10meters which is too powerful)

Thank you

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
