### ISSUE TITLE
mixing View and State

### ISSUE THREAD

**Issue by abiemann** [android/connectivity-samples#138]
The sample code is terrible because view and state are mixed so heavily; it makes it extremely hard to see what's going on and to transfer the necessary business code to an existing code-base.

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
