### ISSUE TITLE
onCharacteristicRead() - Device= handle=46 Status=15

### ISSUE THREAD

**Issue by madhurihr1592** [android/connectivity-samples#15]
I have implemented read and write characteristic. Its working fine with nexus. But with few phones callback is not getting called. I am getting `onCharacteristicRead() - Device= handle=46 Status=15` this error. I have implemented the same way you have done. What does status 15 mean ? Also, in your example bluetooth code is inside a service. why is it so ? cant we write in activity and extend this activity from other activities ?

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
