### ISSUE TITLE
[Android 8.0 (Oreo)] Nexus 5X Oreo (version 8.0 and 8.1.0) does not support Bluetooth search and connection

### ISSUE THREAD

**Issue by jinsoon** [android/connectivity-samples#16]
Hi,

In the Nexus 5X version 7.1.1 or 7.1.2, the HM-10 (or CC41-A) Bluetooth module
There was no big problem in interlocking.

However, Nexus 5X Oreo (version 8.0 and 8.1.0) does not support Bluetooth search and connection.

I would like to know if it is a characteristic of the Android OS or a compatibility issue of the Bluetooth module chip.

Even if your Android OS changes, you should not have any problems with your existing Bluetooth product.

I will contact you if there is any possibility of applying Google patch for this matter.

Thanks.

Log:
D/BluetoothAdapterProperties( 7633): Name is: Nexus 5X
D/BluetoothManagerService( 2853): Bluetooth Adapter name changed to Nexus 5X
D/BluetoothManagerService( 2853): Stored Bluetooth name: Nexus 5X

I/*****   ( 7156): DeviceScanActivity onResume()
I/*****   ( 7156): DeviceScanActivity LeDeviceListAdapter()
D/ObexServerSockets2( 7633): Accepting socket connection...
I/*****   ( 7156): mLeDevices.size() :0
I/*****   ( 7156): mLeDevices.size() :0
D/BluetoothPbapService( 7633): PBAP server with handle:3
I/*****   ( 7156): DeviceScanActivity scanLeDevice()
D/BluetoothPhonePolicy( 7633): UUIDs on ACTION_UUID: [Landroid.os.Parcelable;@327a96d for device 98:D3:32:70:56:7E
D/BluetoothPhonePolicy( 7633): processInitProfilePriorities() - device 98:D3:32:70:56:7E UUIDs [Landroid.os.ParcelUuid;@4d089a2
D/HidService( 7633): getHidService(): returning com.android.bluetooth.hid.HidService@c062633
D/BluetoothAdapter( 7156): startLeScan(): null
D/ObexServerSockets2( 7633): Accepting socket connection...
D/ObexServerSockets1( 7633): Accepting socket connection...
D/BluetoothAdapter( 7156): isLeEnabled(): ON
D/BluetoothMap( 3201): getConnectionState(98:D3:32:70:56:7E)

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
