### ISSUE TITLE
Bluetooth LE Scan not working after configuration changes

### ISSUE THREAD

**Issue by iamlamnguyen-zz** [android/connectivity-samples#17]
I use BLE to connect to a medical device. Everything is normal but when I set date time to the previous date in system Android 7.0 so I can't pair with Bluetooth device. I just only receive a message from BluetoothAdapter.

`11-05 10:26:17.495 16889-16889/com.siclo.medeo.india.dev D/BluetoothAdapter: startLeScan(): null`
`11-05 10:26:17.496 16889-16889/com.siclo.medeo.india.dev D/BluetoothAdapter: STATE_ON`
`11-05 10:26:17.497 16889-16889/com.siclo.medeo.india.dev D/BluetoothAdapter: STATE_ON`
`11-05 10:26:17.497 16889-16889/com.siclo.medeo.india.dev D/BluetoothLeScanner: Start Scan`
`11-05 10:26:17.498 16889-16889/com.siclo.medeo.india.dev D/BluetoothAdapter: STATE_ON`
`11-05 10:26:17.500 16889-16889/com.siclo.medeo.india.dev D/BluetoothAdapter: STATE_ON`
`11-05 10:26:17.502 16889-16889/com.siclo.medeo.india.dev D/BluetoothAdapter: STATE_ON`
`11-05 10:26:17.503 16889-16889/com.siclo.medeo.india.dev D/BluetoothAdapter: STATE_ON`
`11-05 10:26:17.607 16889-16901/com.siclo.medeo.india.dev D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=7 mClientIf=0`
`11-05 10:26:17.617 16889-16889/com.siclo.medeo.india.dev D/ViewRootImpl@4bdb1af[Activity]: ThreadedRenderer.create() translucent=false`

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
