### ISSUE TITLE
Paring to devices

### ISSUE THREAD

**Issue by jitendracodehacker** [android/connectivity-samples#175]
Urgent : The unpaired devices can be paired with entering passkey first time and then after it shall auto connect to paired devices.

**Comment by isaidamier** [comment]
have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there?
