### ISSUE TITLE
GATT error with 133 on onConnectionStateChange

### ISSUE THREAD

**Issue by prasanthmurugan** [android/connectivity-samples#18]
**My Problem**

 **i am  stuck with this problem for more then a week if any Googler out there can you help me !**

After few attempt the GATT service is getting disconnected i don't know the reason.I found that the **onConnectionStateChange** i got the status as **62** and **133**.But i don't know the exact reason or solution to solve the problem. 

**Connection Code:**

     public boolean connectDevice(final BluetoothDevice device) {
        
        try {
            broadcastUpdate(MyUtils.ACTION_GATT_REQUEST,"Before connect called " + mContext);
            if (mContext != null) {

                mBluetoothGatt = device.connectGatt(mContext, false,
                        mGattCallback);

                setmBluetoothGatt(mBluetoothGatt);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return true;
    }

**CallBack**  
   
     @Override
        public void onConnectionStateChange(BluetoothGatt gatt, int status,
                                            int newState) {
            super.onConnectionStateChange(gatt, status, newState);

            String intentAction;
            Log.e(TAG, "onConnectionStateChange: status=>"+status+" newState=>"+newState);
            if (newState == BluetoothProfile.STATE_CONNECTED) {
              
                
            } else if (newState == BluetoothProfile.STATE_DISCONNECTED) {

             }
    }

**Comment by KonovalovaKV** [comment]
Hi guys!
Is there any news to solve this problem? It is very important!

**Comment by nullbeans** [comment]
Hi Guys,

I also faced similar issues. While I didn't manage to fix the issue, I managed to work around it to avoid it. I noticed that my issues disappeared when I did the following:

- Do not do a cancelDiscovery. Let the discovery finish by itself. For some reason when I did a cancel, my subsequent BLE connect attempts were buggy.
- Keep your interactions with the BluetoothGatt in Android's main thread (disconnect, close, discoverServices, etc..). Yup, I know it kind of sucks, but when I did that, 99% of my issues disappeared. for example: **new Handler(ctx.getMainLooper()).post( () -> gatt.close());** . 

My only explaination for this behavior is buggy implementations on the phone vendor's side. Some phones are more buggy than others. Hope this info helps someone.

**Comment by QasimWani** [comment]
> @joe-skb7 . ConnectGATT has 4 parameters. The last one is BluetoothDevice.TRANSPORT_LE. that will fix it.

this didn't fix my issue.

**Comment by Stan14** [comment]
My two cents. Was working with Heart Rate BLE device, device was advertising, had no problems with scanning it but always got 133 when trying to connect.
Turned out connection is allowed _ONLY_  when device is _functioning_, that is, when it is attached to the earlobe and transmits heart rate data. If I disconnect, then took it off, re-scan and try to connect - get 133, put it on my ear, try connect again - no problems whatsoever.

**Comment by M201370367** [comment]
If 133 happens, the use the existing gatt to connect again, do not try to create a new gatt.

**Comment by lior13** [comment]
I see you all are still facing this nightmare.
We used to have a Bluetooth library that caused many troubles. We decided to write a new clean library, so I made a little research and found [this article](https://medium.com/@martijn.van.welie/making-android-ble-work-part-1-a736dcd53b02) VERY useful.
The new library is already in use and it works almost flawless.

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful

**Comment by Shimingli** [comment]
Seeing such a little friend fighting against this shit, I was so cool in my heart, hey, god, help me

**Comment by timethernom** [comment]
I was having this problem consistently whenever there were 2 BLE devices nearby.  Changing the autoconnect parameter on connectGatt() to true fixed the problem.

**Comment by stevenwsg** [comment]
Many years later,  does this proble have new solutation?

**Comment by timethernom** [comment]
2 thing I have learned:
1.  setting autoconnect to true causes fewer connection failures, but can be very slow, like 10's of seconds, which is not acceptable in my case
2. Stopping scanning before attempting to connect improves reliability

**Comment by hoangvu-healthRFID** [comment]
After testing and trying many scenarios, to solve this issue I need to restart the device's BT programming:

1. set autoconnect to false.
2. When receiving error code 133, stop all BT scans or discovery, and also close BTGatt
3. Turn off BT then turn on BT after at least 30s (I found out that some forums mention that after turning off the BT, it need time to completly release all old connection and catch)
4. Start scan/discovery process (this process needs to run to re-connect)
5. Create a new BTGatt to connect

Normally this solution can help to reconnect in the first attempt. sometimes in the third attempt

**Comment by mecoFarid** [comment]
> Many years later, does this proble have new solutation?

No and will never have fixed solution. Different chips on different devices are not easy to handle since Google have decided to give manufacturers freedom on their chipset design. So this will always be **"resolves my problem on XXX devices but still have the same problem on million other devices"**

**Comment by sarn0ld** [comment]
> > Guys,
> > I've found these two blogs that show how to alleviate the problem:
> > https://hellsoft.se/bluetooth-low-energy-on-android-part-1-1aa8bf60717d
> > https://hellsoft.se/bluetooth-low-energy-on-android-part-2-8fdb8ee3bfe9
> > Hope this helps you. It did for me.
> 
> 404, both blog postings no longer exist.

Here are the new links my friend:

https://www.hellsoft.se/bluetooth-le-for-modern-android-development-part-1/
https://www.hellsoft.se/bluetooth-le-for-modern-android-development-part-2/
https://www.hellsoft.se/bluetooth-le-for-modern-android-development-part-3/
https://punchthrough.com/crash-course-in-2m-bluetooth-low-energy-phy/

**Comment by Darshanr5051** [comment]
Hello, 
I am a Newbie Here.

I am facing an error regarding Bluetooth.
"BT_GATT : No Resources"

ca anyone suggest me what should i do ?
