### ISSUE TITLE
android/connectivity-samples cannot scan or advertise

### ISSUE THREAD

**Issue by Ibery-Wong** [android/connectivity-samples#181]
In the android/connectivity-samples sample, the app terminates when I switch the advertiser switch on, I can't use advertiser module. Also scanner doesn't as well.

My device (Huawei Mate 20 Pro) supports BLE. I changed the minSDK to 26 but it doesn't help. Any idea?

Thanks

**Comment by hbollon** [comment]
Same here, all Huawei devices on Android 10 that i tested experience discovery problem on my project.
Before Android 10 it worked very well....

**Comment by isaidamier** [comment]
Were you able to resolve your issue by looking at our [latest  BT sample](https://github.com/android/connectivity-samples/tree/main/BluetoothAdvertisementsKotlin)?  If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow and we will take a look there?

(please feel free to reopen the issue if not yet resolved)
