### ISSUE TITLE
Devices not detected or ScanCallback is not called in Android 6+ Mobile devices

### ISSUE THREAD

**Issue by aya-salama1989** [android/connectivity-samples#183]
ScanCallback is not getting called and other BLE devices are detected at any Android 6+device.

Proposed solution;
1- add COARSE_LOCATION_Permission to manifest 
`    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
2- make sure you enabled location permission from device's settings or request it on runtime if(Build.VERSION.SDK_INT >= 23)
`

**Comment by mwallnoefer** [comment]
And Android > 9 even requires _ACCESS_FINE_LOCATION_: https://developer.android.com/guide/topics/connectivity/bluetooth-le#permissions

**Comment by Laren2121** [comment]
https://github.com/android/connectivity-samples/issues/203

Hope this solves the issue

**Comment by isaidamier** [comment]
have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow and we will take a look there?
