### ISSUE TITLE
sample crashes over Android 8+ devices asking for Foreground permissions

### ISSUE THREAD

**Issue by aya-salama1989** [android/connectivity-samples#184]
proposed solution;
Please add foreground services permission to your manifest

`    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
`

**Comment by isaidamier** [comment]
have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow and we will take a look there?
