### ISSUE TITLE
In leScanCallback device.getName() returns null on few devices

### ISSUE THREAD

**Issue by prasanthmurugan** [android/connectivity-samples#19]
**My problem**

I am developing an application that scans the nearby Bluetooth device and displays in the home screen.But on few devices(i.e moto G,samsung note2) the device name is null on leScanCallback.

**My code**
        
    private BluetoothAdapter.LeScanCallback mLeScanCallback = new BluetoothAdapter.LeScanCallback() {

        @Override
        public void onLeScan(final BluetoothDevice device, final int rssi,
                             byte[] scanRecord) {
           if (device.getName() != null){//<<- Here it null on few device
               //my process          
            }
      }
    };

**Note:**
I need to throw an alert if it return null but i can't do it inside the onlescan because the scanning continuously. Before that i need to throw alert to user based on the bluetooth version is it possible and why on few devices i wont get the device name ? Thanks in advance.

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
