### ISSUE TITLE
AsyncTask is deprecated

### ISSUE THREAD

**Issue by micmader** [android/connectivity-samples#191]
AsyncTask is deprecated.
What are we expected to use?

**Comment by iyadseizer** [comment]
you will use that 
`private static final Exeutor executor = new ThreadPoolExecutor(1,128,1,TimeUnit.SECONDS,new LinkedBlockQueue<Runnable>());
public void startExecute(Callable callable){
executor.execute(new Runnable(){
@Override
public void run(){
callable.call();
}}});`

**Comment by isaidamier** [comment]
have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow and we will take a look there?
