### ISSUE TITLE
Can I get the same application in Xamarin

### ISSUE THREAD

**Issue by ShaileshBhatNP** [android/connectivity-samples#192]
Can anyone send me the same type of sample application using Xamarin..
https://stackoverflow.com/q/62371859/7204954
Thanks in advance..

**Comment by isaidamier** [comment]
have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow and we will take a look there?
