### ISSUE TITLE
有大佬知道这是什么问题吗

### ISSUE THREAD

**Issue by wangyao333** [android/connectivity-samples#209]
Execution failed for task ':react-native-ble-manager:javaPreCompileDebug'.
> Could not resolve all files for configuration ':react-native-ble-manager:debugCompileClasspath'.
   > Failed to transform artifact 'support-v4.aar (com.android.support:support-v4:23.0.1)' to match attributes {artifactType=android-classes, org.gradle.usage=java-api}.
      > Execution failed for AarToClassTransform: C:\Users\24638\.gradle\caches\modules-2\files-2.1\com.android.support\support-v4\23.0.1\9e8da0e4ecf9f63258c7fbd273889252cba2d0c3\support-v4-23.0.1.aar.
         > duplicate entry: META-INF/MANIFEST.MF

**Comment by isaidamier** [comment]
Hi wangyao333,

have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow and we will take a look there?
