### ISSUE TITLE
Why FTM-enabled AP displays does not support 802.11mc ?

### ISSUE THREAD

**Issue by XiangyuTang** [android/connectivity-samples#227]
FTM-enabled AP : ASUS ARCH 17.

When verifying whether the program supports FTM measurements, the ASUS ARCH 17 router is used as an AP, and the AP is currently verified by the WIFI FTM Linux Tool tool that the AP is FTM-enabled and can return ranging results, but when I use the APP scan to the AP shows a STATUS_RESPONDER_DOES_NOT_SUPPORT_IEEE80211MC.

Can anyone explain why? And what is the principle of its recognition of whether the AP supports 802.11mc?

**Comment by isaidamier** [comment]
Hi XiangyuTang,

have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow and we will take a look there?
