### ISSUE TITLE
UWB example exception

### ISSUE THREAD

**Issue by wfuqiang1982** [android/connectivity-samples#293]
I run the UWB example on Android Studio, but there was an exception.  how to solve it? Thank you
Devices : two google  pixel 6 pro 

https://github.com/android/connectivity-samples/assets/88428530/b043a37b-1732-4809-990e-f54fb49870c4

https://github.com/android/connectivity-samples/assets/88428530/faee6e0e-dcf8-4efe-890c-94c38176d1f5

The following exceptions occurred in the controllee through Android studio logcat:

![Bitmap image (5)](https://github.com/android/connectivity-samples/assets/88428530/f9bf640a-316b-4598-9308-3ac2e54a1328)

**Comment by codetang-2417** [comment]
I provided an answer on another similar topic, you need to confirm if your phone's Google GMS service is installed and updated to the latest version. This type of problem is caused by the GMS driver, and you need to update to the latest version. If you confirm that you have updated to the latest level, try restarting the phone, or start Airplane mode and restart the UWB module. I used Samsung S21+for testing, and the underlying driver has some problems, so sometimes you need to restart the UWB module, which can be achieved by starting Airplane mode and restarting the phone. Good luck to you!

**Comment by wfuqiang1982** [comment]
> I provided an answer on another similar topic, you need to confirm if your phone's Google GMS service is installed and updated to the latest version. This type of problem is caused by the GMS driver, and you need to update to the latest version. If you confirm that you have updated to the latest level, try restarting the phone, or start Airplane mode and restart the UWB module. I used Samsung S21+for testing, and the underlying driver has some problems, so sometimes you need to restart the UWB module, which can be achieved by starting Airplane mode and restarting the phone. Good luck to you!

thanks bro，I followed your method to update GMS, and it‘s work. Thank you.
