### ISSUE TITLE
Wifi RTT scan app is  showing all access points are not support rtt.

### ISSUE THREAD

**Issue by sriramsurya** [android/connectivity-samples#60]
Wifi RTT scan app is  showing all access points are not support rtt.
But our access point have IEEE 802.11 standard only.
Please help us on this

**Comment by isaidamier** [comment]
have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there?
