### ISSUE TITLE
read failed, socket might closed or timeout, read ret: -1

### ISSUE THREAD

**Issue by anish01stha** [android/connectivity-samples#66]
How can I handle this error.

**Comment by eugenelyj** [comment]
The same. Do you solve?

**Comment by isaidamier** [comment]
have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, including the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there?
