### ISSUE TITLE
Bluetooth LE how no notify?

### ISSUE THREAD

**Issue by makarna35** [android/connectivity-samples#7]
Hi;
I have this Service ID: 0000ffe0-0000-1000-8000-00805f9b34fb
And Characteristic ID under this Service ID:
0000ffe1-0000-1000-8000-00805f9b34fb

Now to notify Characteristic ID?

Note: I have bluetooth scanner service etc. I need only notify Characteristic ID

**Comment by Vandana0** [comment]
Have you got some solution of write/notification?

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate
