### ISSUE TITLE
if you need to connect another device,you need this:

### ISSUE THREAD

**Issue by gs666** [android/connectivity-samples#70]
https://github.com/googlesamples/android-BluetoothChat/issues/20

private static final UUID MY_UUID_SECURE =
            UUID.fromString("00001101-0000-1000-8000-00805f9b34fb");
    private static final UUID MY_UUID_INSECURE =
            UUID.fromString("00001101-0000-1000-8000-00805f9b34fb");

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate
