### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by Pranesh111** [android/connectivity-samples#75]
Installed the bluetooth chat in two devices(Android M & Android N) & when I m trying to search for nearby device its not detecting

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate
