### ISSUE TITLE
Package R does not exist

### ISSUE THREAD

**Issue by AlinPlesca** [android/connectivity-samples#77]
Hello. I am dealing with this problem. When I press run, an error occurs and said: package R does not exist. How can I solve the problem? 

SOLVED!!! You need to highlight the "R" which is red in code and after press "alt + Enter" and should be alright.

Thanks

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate
