### ISSUE TITLE
Why I can't send a large amount of data via Bluetooth Android?

### ISSUE THREAD

**Issue by koz01** [android/connectivity-samples#79]
I can't send along data, although I change the size of "buffer". What should I do?
Please help me.

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

**Comment by isaidamier** [comment]
Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
