### ISSUE TITLE
Crash when there no device was found but click the list item

### ISSUE THREAD

**Issue by tianzry** [android/connectivity-samples#80]
In the code file :DeviceListActivity.java, line 175, as the code show following, cause the crash:

`            // Get the device MAC address, which is the last 17 chars in the View`
            `String info = ((TextView) v).getText().toString();`
           ` String address = info.substring(info.length() - 17);`

Once we add other String into Listview as the code line 125 do:

`String noDevices = getResources().getText(R.string.none_paired).toString();`
`pairedDevicesArrayAdapter.add(noDevices);`

and then we click the item"No devices found", the app crash, because we get a wrong MAC.

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
