### ISSUE TITLE
Code does not work

### ISSUE THREAD

**Issue by behelit** [android/connectivity-samples#81]
Targets sdk 25 but does not support it.
Unable to scan for devices due to missing permissions, even though the first scan works for some reason, guess it's just more google poor programming bugs as usual.
Please update your terrible code so that programmers can actually build for your terrible OS.
It's bad enough that Bluetooth is a nightmare to work with on android but pair that with your outdated code, 500 bt changes per release, irrelevant permissions, and confusion requirements, and you have one mess of a turd that no one wants to touch.

**Comment by isaidamier** [comment]
We have recently updated our samples. Have you been able to resolve the issue you had encountered? If not might you be able to clarify based on our latest samples?
- The specific project that pertains to the issue (for example: the 'BluetoothLeGatt' project)
- Steps to repro the issue, the API version and Android device model
- If the issue is not about a sample, would you please file on Stackoverflow or [the issue tracker](https://b.corp.google.com/issues/) and we will take a look there? 
- Please include code snippets as appropriate

Also we have a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful
